### ISSUE TITLE
Improve client-side decorations on Windows

### ISSUE THREAD

**Issue by reflectronic** [theCheeseboard/libcontemporary#2]
- [x] Ensure we don't create a layered window
- [x] Implement proper drag regions
- [x] Make sure Aero Snap works
- [x] Make sure Windows 11 [snap layouts](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu) work

**Comment by vicr123** [comment]
Most CSD issues have been fixed as of df4086b
